### ISSUE TITLE
Add RODAS

### ISSUE THREAD

**Issue by ChrisRackauckas** [luchr/ODEInterface.jl#10]
It seems that the only ODE solvers from Hairer's set are the RODAS methods (and the deprecated ROS4, but that's probably not necessary). Is there any fundamental limitation that caused this that makes it different than the other solvers? Or is it just about finding the time to wrap it?

**Comment by luchr** [comment]
The *very* first version for an interface to RODAS is in the "devel" branch.

The current tests are successful for Julia v0.4 and v0.5 in Linux. 
For the current v0.6-dev-trunk I have to check the interesting error 

> The applicable method may be too new: running in world age 20550, while current world is 20756.

Test cases for the new right-hand-side time-derivative Option `OPT_RHSTIMEDERIV` are still missing.

In addition I want to refactor the code (internally, i.e. without changing the API) in order to reuse common parts.

**Comment by ChrisRackauckas** [comment]
>The applicable method may be too new: running in world age 20550, while current world is 20756.

Yeah, that error is currently happening to a lot of libraries, so it's a bug with the current build and not with the implementation. There are a few other errors in ODEInterface which was causing it to fail on v0.6 before this though, but it should just need minor fixes. But thanks for the Christmas gift 👍 , I'll have some fun trying it out.

**Comment by ChrisRackauckas** [comment]
I added RODAS to ODEInterfaceDiffEq and it's ready to benchmark, so this seems all done now. Thanks!
