### ISSUE TITLE
Have BinaryBuilder recipes to get these into Yggdrasil

### ISSUE THREAD

**Issue by ViralBShah** [luchr/ODEInterface.jl#28]
It would be nice to have BB recipes to get the fortran libs into Yggdrasil. I am happy to help.

**Comment by luchr** [comment]
OK. Then let's see. BB recipes and JLLwrappers are completely new to me. Here are my first impressions and I've some questions because some "puzzle-pieces" are missing (in my understanding):

First there is the BB recipe, like e.g. [LibGit2/build_tarballs.jl](https://github.com/JuliaPackaging/Yggdrasil/blob/master/L/LibGit2/build_tarballs.jl) where the main part is a bash(!!)-script (often given as a raw-string inside such a julia file; sometimes the string is created dynamically with julia, like here [FFMPEG](https://github.com/JuliaPackaging/Yggdrasil/blob/master/F/FFMPEG/common.jl#L16)). First thing which is new for me: Is Bash a better "language" to call other programs (like compilers and linkers) than julia?

**Question 1** So I have to rewrite [my build.jl](https://github.com/luchr/ODEInterface.jl/blob/master/deps/build.jl#L30) (where I was able to use Dicts and other nice features of julia to dynamically/easily create the compiler and linking flags) in bash? Is there no way to use a more modern language, like e.g. julia, to call the compilers/linkers?

Then I use BinaryBuilder to build the ".jll". Then I try to use this. In the [docs: LibraryProduct](https://docs.binarybuilder.org/stable/jll/#LibraryProduct) is see I should use ```ccall``` with the method-name and a constant (defined by the jll).

**Question 2** How to get the method-pointers? To also support that users can use their compiler to compile the libs (instead of the one I call in my build-script) I used [my solution to cope with different naming conventions](https://github.com/luchr/ODEInterface.jl/blob/master/src/DLSolvers.jl#L64) and I return the found method as pointer. Is this still possible?

**Question 3** Directly connected to Q2: With method pointers I was able (at compile time, depending on the choice how many bits a integer in Fortran had) to switch/exchange/use the right set of pointers, [example](https://github.com/luchr/ODEInterface.jl/blob/master/src/Dopri5.jl#L126). Do I now have to pass lib-constant and method-name instead (instead of a simple method-pointers)?

**Question 4** Is it (in principle) possible to keep supporting users who supply their own version of the compiled libs (just the persons who know what a compiler is, have their own, perhaps even paid for their own and know how to use it)? At the moment they can just call [loadODESolvers](https://github.com/luchr/ODEInterface.jl/blob/master/src/DLSolvers.jl#L97) with paths to look first for the libs (so it's easy to switch between libs with and without debugsymbols, etc.)?

I'am a big fan of Libdl and its simple methods (like ```dlsym```). The longer I read BinaryBuilder (and the JLLwrapper stuff) the more question marks I have. Wrappers here and wrappers there. At the end I need a method pointer. That's all. Having the pointer is the important thing (not to handle anymore naming conventions of different compilers, etc.). My personal definition of a wrapper(-output/return value) are [these two structs](https://github.com/luchr/ODEInterface.jl/blob/master/src/DLSolvers.jl#L14).

I hope for some answers to have an estimate how much work this is and to see if this is an feature-upgrade, same-feature-thingy or feature-downgrade (Q4).

**Comment by ViralBShah** [comment]
I think you have read more about BinaryBuilder than you need to. :-)

From the perspective of this package, the bash script in Yggdrasil will include build recipes for the fortran libraries and build binaries on all the architectures, generate the wrapper package, and register it (it is all transparent to you - as someone who has built several BB recipes, I can tell you that I have not needed to know any more details). As a package author, you then declare a dependency on this generated JLL package in your Project.toml. All your existing stuff should pretty much work just as is. If you want to allow user provided versions of libraries, we can build an escape hatch through an environment variable, the way GR.jl does it.

I don't think this answers all your questions (and I need to understand Q3 and Q4 better) - although I really don't think anything should change in the package code except for the path where the libraries are loaded from. It is also a relatively simple experiment - in that we can build the binaries and try this out in a PR. If it seems like it is more than what is "same-feature-thingy", can always just leave things the way they are.

**Comment by luchr** [comment]
Here is my first attempt for a BB recipe: [gist](https://gist.github.com/luchr/eb25d292fe9cb5be03f2ab89c3753e5d#file-build_tarballs_v1-jl).

I've updated my [build.jl inside ODEInterface](https://github.com/luchr/ODEInterface.jl/blob/987d0e2cffd1d7f2fd8e378b7292bed4bf451c06/deps/build.jl). If called with an ENV-Option set, now it creates the bash-script with the `gfortran`-calls. This bash-script I've used inside the BB recipe [in order to avoid doing this by hand, reinventing the wheel].

Is this, how it is supposed to be?

**Comment by ViralBShah** [comment]
I say it looks good enough to open a PR on Yggdrasil and see if it goes through. And if it does, then add all the other platforms as well. We can iterate the recipe there. And once it is successfully built and registered, it can be added to the Project.toml here. Thanks for putting it together!

**Comment by luchr** [comment]
I've created a pull-request (with all platforms): https://github.com/JuliaPackaging/Yggdrasil/pull/2523

But I've still a delicate question (sorry):
What if I don't want to add the jll-Package as dependency to the `Project.toml`? Is this even thinkable or do I have to expect some "stoning sentence"?
I want to try the following (I don't know at the moment if this is doable, I think it is): Support all of the 3 methods:

- User can add the jll-package (manually) and if `ODEInterface.jl` finds it in the package list, then it tries to use this package.
- User can call `ODEInterface.loadODESolvers` with path and then `ODEInterface.jl` tries to use these libs there (independently how they were produced/compiled/linked).
- User can use the `ODEInterface`-build-script which tries to build the libs (at the user's host).

The last two possibilities (of the three above) are already possible since a very long time [since round about Julia v0.4].

**Comment by ViralBShah** [comment]
It is your package - and you are free to do what is best! :-)

My suggestion is the following - make it a dependency and a default thing that works out of the box. I will bet you that 90% of the people will be relieved they don't need to compile anything. But then have an escape hatch (usually done with an environment variable) to use system installed binaries externally (basically ignores whatever was pulled in from Yggdrasil or even to trigger the build.jl in the way it currently builds). In fact many packages do exactly this.

**Comment by luchr** [comment]
> It is your package - and you are free to do what is best! :-)

:-)

> My suggestion is the following - make it a dependency and a default thing that works out of the box. I will bet you that 90% of the people will be relieved they don't need to compile anything. 

It seems (to me) the "target audience"/"target users" have changed over time. I remember back the times where this package started as an Interface (hence this crazy name) and had no build-script at all and the users (and my students) had to build *their* libraries themselves. ... ... Back to future:

> But then have an escape hatch (usually done with an environment variable) to use system installed binaries externally (basically ignores whatever was pulled in from Yggdrasil or even to trigger the build.jl in the way it currently builds). In fact many packages do exactly this.

OK. If I survive the how-do-you-dare-you-are-not-using-a-proper-language-like-Bash-and-Makefile-discussion in the pull-request [I really don't want to update/support two building-environments] I'll try your suggestion.

Thank you very much for your feedback.

**Comment by ViralBShah** [comment]
Merged! Let's see if the new binaries actually work :-)

The package is registered: https://github.com/JuliaRegistries/General/pull/29837

**Comment by luchr** [comment]
I'll test it in the next days. First I have to generate a new branch for the older versions 0.7 ≤ julia version ≤ 1.2 (as far as I can see, artifacts are not possible with this versions) and then extend the code for the 1.3 ≤ julia  master-branch (by addind the additional jll-dependency) and extending the loadODESolver.

[Branches and Versions](https://github.com/luchr/ODEInterface.jl/blob/master/VERSIONS.md).

**Comment by ViralBShah** [comment]
That is easy to do - just add the equivalent of these 3 lines to build.jl: https://github.com/jump-dev/Clp.jl/blob/master/deps/build.jl#L1-L3

That should give you a way to support the old versions.

**Comment by luchr** [comment]
OK. It took me some time, but now I hope I've understood this: One can *add* the package `ODEInterface_jll.jl` also in Julia ≥ 1.0  [but `using` it will give an error if 1.0 ≤ juliva_version ≤ 1.2]. So I only need an extra branch for julia v0.7 because there even adding is impossible because of the compat settings in [ODEInterface_jll.jl's Project.toml](https://github.com/JuliaBinaryWrappers/ODEInterface_jll.jl/blob/main/Project.toml).

**Comment by ViralBShah** [comment]
I personally not worry about anything older than 1.0, especially 0.7 since it was a transition only release.

**Comment by luchr** [comment]
The last feature ("colnew" solver) I backported to v0.4, v0.5 and v0.6. Perhaps time for me to stop supporting julia versions smaller than 0.7 ... and perhaps 0.7 also.
Thank you.

**Comment by ViralBShah** [comment]
Yes, please don't! I personally only focus on 1.3+ - when multi-threading and artifacts were added. Also, it likely that 1.6 or 1.7 will be the new LTS.

**Comment by luchr** [comment]
> Merged! Let's see if the new binaries actually work :-)

Here are the results: I added [a method to extract the handles from the jll](https://github.com/luchr/ODEInterface.jl/blob/259f3a5e02994e54ba6ff243d07c4455c88c21ae/src/DLSolvers.jl#L65-L81)  and added a flag in the [loadODESolvers](https://github.com/luchr/ODEInterface.jl/blob/259f3a5e02994e54ba6ff243d07c4455c88c21ae/src/DLSolvers.jl#L116) method so that the user has the full choice (self-built, locally built with build-script or jll). And for julia 1.3 or newer the default is to use the libs from the jll as you suggested.

[Travis for Julia 1.0.5](https://travis-ci.org/github/luchr/ODEInterface.jl/jobs/758770839#L358) using the locally built libs and [Travis for Julia 1.5.3](https://travis-ci.org/github/luchr/ODEInterface.jl/jobs/758770844#L392) using the libs from the jll loaded with Artifacts.

In the next days I'll improve the documentation for the new situation and then there will be a new version of ODEInterface.

One (hopefully last) question:
Are there any special "events" where I have to trigger a rebuild or where I have to do other actions?

Thank you for your input. It helped me a lot.

**Comment by ViralBShah** [comment]
This is great. Thank you for putting this together! I don't think there are any other events. Probably address anything that shows up as the new versions propagate. I suppose you will need to tag a new release of this package when ready, so that users can try out the new binaries.

I think this issue is addressed - so closing.
