### ISSUE TITLE
Tag?

### ISSUE THREAD

**Issue by ChrisRackauckas** [luchr/ODEInterface.jl#29]
It would be good to have a tagged version with the JLLs.

**Comment by luchr** [comment]
Hi,

sorry. I don't know what you mean:

(a) a version of the ODEInterface package *together* with the JLLs?
(b) a tag for the versions where the sources are inside that were used to built the JLLs?
(c) something else?

Or do you mean a new *release*. OK. Tag v0.5.0 is now also a release (since a few moments ago). 

If you mean something else: Can you elborate a little bit more? Perhaps also with a small hint, why?

**Comment by ChrisRackauckas** [comment]
I see, yeah it just wasn't showing on the repo. You should really setup TagBot to fix that. https://github.com/luchr/ODEInterface.jl/pull/30

**Comment by luchr** [comment]
I literally don't understand one word. Thank you for closing the ticket.

I'll try to read the documentation for [TagBot](https://github.com/JuliaRegistries/TagBot) and see what it is for and hope, I then can (re-)interpret your words.
